core/multipolimeros/urls.py
from django.urls import path
from core.multipolimeros.views import *

app_name = 'multipolimeros'

urlpatterns = [
    path('dashboard/', dashboard.as_view(), name='dashboard'),
    # URLS DE PROSPECTOS
    path('crear-prospecto/', crearProspecto.as_view(), name='crear-prospecto'),
    path('editar-prospecto/<int:pk>/', editarProspecto.as_view(), name='editar-prospecto'),
    path('crear-pdf/<int:id>/', crearPdfProspectos,  name='crear-pdf'),
    # URLS DE CLIENTES
    path('crear-cliente/', crearCliente.as_view(), name='crear-cliente'),
    path('editar-cliente/<int:pk>/', editarCliente.as_view(), name='editar-cliente'),
    path('crear-pdf-cliente/<int:id>/', crearPdfClientes,  name='crear-pdf-cliente'),
    # URLS DE CREDITOS
    path('crear-credito/', crearCredito.as_view(), name='crear-credito'),
    path('editar-credito/<int:pk>/', editarCredito.as_view(), name='editar-credito'),
    path('crear-pdf-credito/<int:id>/', crearPdfCreditos,  name='crear-pdf-credito'),
]

system/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from core.enigmaControl.views import presupuestosViewSet, usuariosViewSet
from system import settings
from django.conf.urls.static import static

router = DefaultRouter()
router.register(r'usuarios', usuariosViewSet)
router.register(r'presupuestos', presupuestosViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.enigma.urls')),
    # URLS DE ENIGMA
    path('erp/', include('core.enigmaErp.urls')),
    path('control/', include('core.enigmaControl.urls')),
    path('ventas/', include('core.enigmaVentas.urls')),
    path('administracion/', include('core.enigmaAdmin.urls')),\
    # URLS DE MULTIPOLIMEROS
    path('multipolimeros/', include('core.multipolimeros.urls')),
    # URLS DE TERCEROS
    path('accounts/', (include(('django.contrib.auth.urls', 'auth'), namespace='auth' ))),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include(router.urls)), 
]

if settings.DEBUG:
    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/multiP/dashboard.html
{% extends "baseDashboard.html" %}


{% block content %}
  

<div class="main-content mb-auto" data-aos="fade-down">
  <p class="text-center h2">Hola {{user.username}}, ¿Qué vamos a hacer hoy? (Multipolimeros)</p>
  <div class="container" data-title="Bienvenido a ENIGMA" data-intro="En enigma podrás agilizar tus procesos de una manera sumamente intuitiva" data-position="auto">
      <div class="row mb-auto">
          <div class="col-lg-4">
            <div class="card text-center my-5" data-title="Modulo de ventas" data-intro="Con el módulo de ventas podrás realizar tus mantenimientos, editarlos, guardarlos en PDF, compartirlos, también podrás registrar pedidos.">
                <div class="card-header">
                  Registrar prospecto
                  <i class="fas fa-users"></i>
                </div>
                <div class="card-body">
                  <p class="card-text text-center">Registra un prospecto con los formularios de Multipolimeros </p>
                  <a href="{% url 'multipolimeros:crear-prospecto' %}" class="btn btn-primary">¡Vamos!</a>
                </div>
              </div>
          </div>

          <div class="col-lg-4">
            <div class="card text-center my-5" data-title="Modulo de control" data-intro="En el módulo de control encontrarás formularios para llevar un mejor registro de lo acontecido, visitas, observaciones, reportes.">
                <div class="card-header">
                  Registra un cliente
                  <i class="fas fa-user"></i>
                </div>
                <div class="card-body">
                  <p class="card-text text-center">Registra un cliente con los formularios de multipolimeros</p>
                  <a href="{% url 'multipolimeros:crear-cliente' %}" class="btn btn-primary">¡Vamos!</a>
                </div>
              </div>
          </div>

          <div class="col-lg-4">
            <div class="card text-center my-5" data-title="Modulo de gráficas" data-intro="En el módulo de administración podrás visualizar los rendimientos, las ventas de los vendedores, tendras acceso a todos los datos globales siempre y cuando seas administrador">
                <div class="card-header">
                  Solicitud de crédito
                  <i class="fas fa-coins"></i>
                </div>
                <div class="card-body">
                  <p class="card-text text-center">Registra una solicitud de crédito con los formularios de Multipolimeros</p>
                  <a href="{% url 'multipolimeros:crear-credito' %}" class="btn btn-primary">¡Vamos!</a>
                </div>
              </div>
          </div>
      </div>
  </div>
</div>


<div class="container">
  <canvas id="myChart" width="400" height="150px"></canvas>
</div>

<div class="table-responsive my-3">
            <p class="text-center h2">Registro de prospectos</p>
            <table id="tablaProspectos" class="table align-middle mb-5">
                <thead>
                    <tr>
                        <th>Fecha</th>
                        <th>Razón social</th>
                        <th>RFC</th>
                        <th>Correo</th>
                        <th>Celular</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for p in prospectos %}
                        <tr>
                            <td>{{p.Fecha}}</td>
                            <td>{{p.RazonSocial}}</td>
                            <td>{{p.Rfc}}</td>
                            <td>{{p.CorreoElectronico}}</td>
                            <td>{{p.TelefonoCelular}}</td>
                            <td>
                                <a href="{% url 'multipolimeros:editar-prospecto' p.pk %}" class="btn btn-primary">
                                    <i class="fas fa-pen"></i>
                                </a>
                                <a href="{% url 'multipolimeros:crear-pdf' p.pk %}" class="btn btn-success">
                                    <i class="fas fa-file-pdf"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>


        <div class="table-responsive my-3">
            <p class="text-center h2 my-3">Registro de clientes</p>
            <table id="tablaClientes" class="table align-middle mb-5">
                <thead>
                    <tr>
                        <th>Fecha</th>
                        <th>Razón social</th>
                        <th>RFC</th>
                        <th>Correo</th>
                        <th>Celular</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for c in clientes %}
                        <tr>
                            <td>{{c.Fecha}}</td>
                            <td>{{c.RazonSocial}}</td>
                            <td>{{c.Rfc}}</td>
                            <td>{{c.CorreoElectronico}}</td>
                            <td>{{c.TelefonoCelular}}</td>
                            <td>
                                <a href="{% url 'multipolimeros:editar-cliente' c.pk %}" class="btn btn-primary">
                                    <i class="fas fa-pen"></i>
                                </a>
                                <a href="{% url 'multipolimeros:crear-pdf-cliente' c.id %}" class="btn btn-success">
                                    <i class="fas fa-file-pdf"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

         <div class="table-responsive my-3">
            <p class="text-center h2">Registro de créditos</p>
            <table id="tablaCreditos" class="table align-middle mb-5">
                <thead>
                    <tr>
                        <th>Fecha</th>
                        <th>Razón social</th>
                        <th>RFC</th>
                        <th>Correo</th>
                        <th>Celular</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for credito in creditos %}
                        <tr>
                            <td>{{credito.Fecha}}</td>
                            <td>{{credito.RazonSocial}}</td>
                            <td>{{credito.Rfc}}</td>
                            <td>{{credito.CorreoElectronico}}</td>
                            <td>{{credito.TelefonoCelular}}</td>
                            <td>
                                <a href="{% url 'multipolimeros:editar-credito' credito.pk %}" class="btn btn-primary">
                                    <i class="fas fa-pen"></i>
                                </a>
                                <a href="{% url 'multipolimeros:crear-pdf-credito' credito.id %}" class="btn btn-success">
                                    <i class="fas fa-file-pdf"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
 
{% endblock content %}


{% block scripts %}
<script>
  const ctx = document.getElementById('myChart');
  const myChart = new Chart(ctx, {
    type: 'bar',
    data: {
      labels: ['Mis prospectos', 'Mis clientes', 'Mis créditos'],
      datasets: [{
        label: 'Mis estadisticas',
        fill: true,
        data: [{{prospectos.count}}, {{clientes.count}}, {{creditos.count}}],
        backgroundColor: [
          'rgba(52, 152, 219,1.0)',
          'rgba(155, 89, 182,1.0)',
          'rgba(46, 204, 113,1.0)',
          'rgba(26, 188, 156,1.0)',
        ],
        borderColor: [
          'rgba(52, 152, 219,1.0)',
          'rgba(155, 89, 182,1.0)',
          'rgba(46, 204, 113,1.0',
          'rgba(26, 188, 156,1.0)'
        ],
        borderWidth: 1
      }]
    },
    options: {
        scales: {
            y: {
              beginingAtZero: true
            }
        }
    }
  });
</script>

<script>
  $(document).ready(function () {
        $('#tablaProspectos').DataTable({
            "language": {
                "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
            },
            responsive: false,
        });

         $('#tablaClientes').DataTable({
            "language": {
                "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
            },
            responsive: false,
        });

        $('#tablaCreditos').DataTable({
            "language": {
                "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
            },
            responsive: false,
        });
    });
</script>
{% endblock scripts %}