core/enigmaControl/urls.py
from django.urls import path
from core.enigmaControl.views import *

app_name = 'enigmaControl'

urlpatterns = [
    path('', dashboardControl.as_view(), name='indexControl'),
    # CONTROL DE VISITAS
    path('crear-visita/', crearControlVisitas.as_view(), name='crearVisita'),
    path('editar-visita/<int:pk>/', editarControlVisitas.as_view(), name='editarVisita'),
    # CONTROL DE REPORTES
    path('crear-reporte/', crearControlReportes.as_view(), name='crearReporte' ),
    path('editar-reporte/<int:pk>', editarControlReportes.as_view(), name='editarReporte'),
    # CONTROL DE PRESUPUESTOS
    path('presupuestos/', presupuestos.as_view(), name='presupuestos'),
    path('eliminar-presupuesto/<int:id>', eliminarPresupuesto, name='eliminarPresupuesto'),
    path('editar-presupuesto/<int:pk>', actualizarPresupuesto.as_view(), name='editarPresupuesto'),
    path('crear-presupuesto/', crearPresupuesto.as_view(), name='crearPresupuesto'),
    path('eliminar-presupuesto-tabla/<int:id>', eliminarPresupuestoTabla, name='eliminarPresupuestoTabla')
]

system/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from core.enigmaControl.views import presupuestosViewSet, usuariosViewSet
from system import settings
from django.conf.urls.static import static

router = DefaultRouter()
router.register(r'usuarios', usuariosViewSet)
router.register(r'presupuestos', presupuestosViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.enigma.urls')),
    # URLS DE ENIGMA
    path('erp/', include('core.enigmaErp.urls')),
    path('control/', include('core.enigmaControl.urls')),
    path('ventas/', include('core.enigmaVentas.urls')),
    path('administracion/', include('core.enigmaAdmin.urls')),\
    # URLS DE MULTIPOLIMEROS
    path('multipolimeros/', include('core.multipolimeros.urls')),
    # URLS DE TERCEROS
    path('accounts/', (include(('django.contrib.auth.urls', 'auth'), namespace='auth' ))),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include(router.urls)), 
]

if settings.DEBUG:
    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/enigmaControl/models.py
from enum import unique
from pyexpat import model
from random import choices
from django.db import models
from django.contrib.auth.models import User
from django.forms import model_to_dict

from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings

from django import forms

from core.enigmaVentas.models import MantenimientoClientes

from django.db.models import Sum


class controlVisitas(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name='usuarioVisitas')
    id = models.AutoField(primary_key=True)
    fecha = models.CharField(max_length=100, blank=False)
    nombreVisita = models.CharField(max_length=100)
    razonVisita = models.CharField(max_length=200)
    duracionVisita = models.TimeField()
    observaciones = models.TextField(max_length=200)

    class Meta:
        verbose_name = 'Control de Visitas'
        verbose_name_plural = 'Control de Visitas'
        ordering = ['-id']

    def to_json(self):
        item = model_to_dict
        item['id'] = self.id
        item['usuario'] = self.usuario.username
        item['fecha'] = self.fecha
        item['nombreVisita'] = self.nombreVisita
        item['razonVisita'] = self.razonVisita
        item['duracionVisita'] = self.duracionVisita
        item['observaciones'] = self.observaciones
        return item

    def __str__(self):
        return f'Visita de {self.nombreVisita} - {self.fecha}'


class reportesControl(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name='usuarioReportes')
    id = models.AutoField(primary_key=True)
    fechaReporte = models.CharField(max_length=100, blank=False)
    nombreReporte = models.CharField(max_length=200)
    notificarReporte =models.CharField(max_length=200)
    descripcionReporte = models.TextField(max_length=200)

    class Meta:
        verbose_name = 'Reportes de Control'
        verbose_name_plural = 'Reportes de Control'

    def __str__(self):
        return f'Reporte de {self.nombreReporte} - {self.fechaReporte}'


MESES = (
    ('Enero', 'Enero'),
    ('Febrero', 'Febrero'),
    ('Marzo', 'Marzo'),
    ('Abril', 'Abril'),
    ('Mayo', 'Mayo'),
    ('Junio', 'Junio'),
    ('Julio', 'Julio'),
    ('Agosto', 'Agosto'),
    ('Septiembre', 'Septiembre'),
    ('Octubre', 'Octubre'),
    ('Noviembre', 'Noviembre'),
    ('Diciembre', 'Diciembre')
)

class PresupuestoModelo(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name='usuarioPresupuesto')
    id = models.AutoField(primary_key=True)
    mesPresupuesto = models.CharField(max_length=100, choices=MESES, default='Enero', unique=True)

    class Meta:
        verbose_name = 'Presupuesto'
        verbose_name_plural = 'Presupuestos'

    def __str__(self):
        return f'Presupuesto de {self.mesPresupuesto}'


class PresupuestoTabla(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name='usuarioPresupuestos')
    id = models.AutoField(primary_key=True)
    presupuesto = models.ForeignKey(PresupuestoModelo, on_delete=models.CASCADE, related_name='presupuesto')
    razonSocial = models.ForeignKey(MantenimientoClientes, on_delete=models.CASCADE, related_name='razonSocial', null=True)
    ventasObjetivo = models.BigIntegerField(blank=True, null=True)
    ventasRealizadas = models.BigIntegerField(blank=True, null=True)
    cobranzaObjetivo = models.BigIntegerField(blank=True, null=True)
    cobranzaRealizada = models.BigIntegerField(blank=True, null=True)

    def getVentasPercentage(self):
        try:
            return round((self.ventasRealizadas / self.ventasObjetivo) * 100, 2)
        except:
            return 0

    def getCobranzaPercentage(self):
        try:
            return round((self.cobranzaRealizada / self.cobranzaObjetivo) * 100, 2)
        except:
            return 0

    @property
    def get_ventas(self):
        return sum([item.ventasRealizadas for item in self.presupuesto.presupuestotabla_set.all()])


    class Meta:
        verbose_name = 'Presupuestos Tabla'
        verbose_name_plural = 'Presupuestos Tabla'

    def __str__(self):
        return f'Presupuesto de {self.usuario.username} - {self.razonSocial}'

core/enigmaControl/forms.py
from tkinter import W, Widget
from django import forms
from core.enigmaVentas.models import MantenimientoClientes
from core.enigmaControl.models import PresupuestoTabla, controlVisitas, reportesControl, PresupuestoModelo

class controlVisitaForm(forms.ModelForm):

    class Meta:
        model = controlVisitas
        exclude = ['usuario']
        fields = '__all__'


class controlReportesForm(forms.ModelForm):

    class Meta:
        model = reportesControl
        exclude = ['usuario']
        fields = '__all__'

class presupuestoForm(forms.ModelForm):

    class Meta:
        model = PresupuestoModelo
        exclude = ['usuario']
        fields = '__all__'






class presupuestoTablaForm(forms.ModelForm):
    
    class Meta:
        model = PresupuestoTabla
        exclude = ['usuario']
        fields = '__all__'

core/enigmaControl/views.py
from distutils.log import error
from http.client import HTTPResponse
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
# DECORADORES Y MIXINS
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
#VISTAS GENERICAS
from django.views.generic import TemplateView, FormView, UpdateView, DeleteView
#MODELS Y FORMS
from core.enigmaControl.forms import *
from django.contrib.auth.models import User
from core.enigmaControl.models import *
from django.contrib import messages
from django.db.models import Sum

from serializers.presupuestosSerializer import PresupuestoTablaSerializer, UsuariosSerializer

from rest_framework import viewsets




class dashboardControl(LoginRequiredMixin,TemplateView):
    template_name = 'enigmaControl/dashboardControl.html'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Control - Enigma'
        context['version'] = '1.0.1'
        context['visitas'] = controlVisitas.objects.filter(usuario=self.request.user).count()
        context['visitasTabla'] = controlVisitas.objects.filter(usuario=self.request.user)
        context['reportes'] = reportesControl.objects.filter(usuario=self.request.user).count()
        context['reportesTabla'] = reportesControl.objects.filter(usuario=self.request.user)
        return context


#  VISTAS DEL CONTROL DE VISITAS

class crearControlVisitas(LoginRequiredMixin,FormView):
    template_name = 'enigmaControl/formularios/controlVisitas.html'
    form_class = controlVisitaForm
    success_url = 'enigmaControl:indexControl'
    

    def form_valid(self, form):
        form.save(commit=False)
        form.instance.usuario = self.request.user
        form.save()
        messages.success(self.request, '¡Registro creado exitosamente!')
        return HttpResponseRedirect(reverse(self.success_url))

    def form_invalid(self, form):
        messages.error(self.request, '¡Algo ha salido mal!')
        return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Control de Visitas - Enigma'
        context['version'] = '1.0.1'
        context['subtitle'] = 'Registro de nueva visita'
        return context


class editarControlVisitas(LoginRequiredMixin, UpdateView):
    model = controlVisitas
    form_class = controlVisitaForm
    template_name = 'enigmaControl/formularios/controlVisitas.html'
    success_url = 'enigmaControl:indexControl'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Editar visita - Enigma'
        context['version'] = '1.0.1'
        context['subtitle'] = 'Edición de visita'
        return context

    def get_success_url(self):
        messages.success(self.request, '¡Visita actualizada con éxito!')
        return reverse_lazy(self.success_url)




# VISTAS DEL CONTROL DE REPORTES

class crearControlReportes(LoginRequiredMixin, FormView):
    template_name = 'enigmaControl/formularios/controlReportes.html'
    form_class = controlReportesForm
    success_url = 'enigmaControl:indexControl'

    def form_valid(self, form):
        form.save(commit=False)
        form.instance.usuario = self.request.user
        form.save()
        messages.success(self.request, '¡Registro creado éxitosamente!')
        return HttpResponseRedirect(reverse(self.success_url))

    def form_invalid(self, form):
        messages.error(self.request, '¡Algo ha salido mal!')
        return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Control de Visitas - Enigma'
        context['version'] = '1.0.1'
        context['subtitle'] = 'Registro de nuevo reporte'
        return context


class editarControlReportes(LoginRequiredMixin, UpdateView):
    model = reportesControl
    form_class = controlReportesForm
    template_name = 'enigmaControl/formularios/controlReportes.html'
    success_url = 'enigmaControl:indexControl'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Editar reporte - Enigma'
        context['version'] = '1.0.1'
        context['subtitle'] = 'Edición de reporte'
        return context

    def get_success_url(self):
        messages.success(self.request, 'Reporte actualizado con éxito!')
        return reverse_lazy(self.success_url)

# Presupuestos

class presupuestos(LoginRequiredMixin, FormView):
    template_name = 'enigmaControl/presupuestos.html'
    form_class = presupuestoForm
    success_url = 'enigmaControl:presupuestos'

    def form_valid(self, form):
        form.save(commit=False)
        form.instance.usuario = self.request.user
        form.save()
        messages.success(self.request, 'Presupuesto creado éxitosamente!')

        tabla = PresupuestoTabla(
            presupuesto = form.instance,
            usuario = self.request.user,
        )

        tabla.save()


        return HttpResponseRedirect(reverse(self.success_url))

    def form_invalid(self, form):
        messages.error(self.request, '¡Algo ha salido mal!')
        return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Presupuestos - Enigma'
        context['version'] = '1.0.1'
        context['presupuestos'] = PresupuestoModelo.objects.all()
        context['presupuestosTabla'] = PresupuestoTabla.objects.filter(usuario=self.request.user)
        context['objetivoVentas'] = PresupuestoTabla.objects.filter(usuario=self.request.user).aggregate(Sum('ventasObjetivo'))
        context['realVentas'] = PresupuestoTabla.objects.filter(usuario=self.request.user).aggregate(Sum('ventasRealizadas'))
        context['objetivoCobranza'] = PresupuestoTabla.objects.filter(usuario=self.request.user).aggregate(Sum('cobranzaObjetivo'))
        context['realCobranza'] = PresupuestoTabla.objects.filter(usuario=self.request.user).aggregate(Sum('cobranzaRealizada'))
        context['userId'] = self.request.user.id
        return context

def eliminarPresupuesto(request, id):
    presupuesto = PresupuestoModelo.objects.get(id=id)
    presupuesto.delete()
    messages.success(request, 'Presupuesto eliminado con éxito!')
    return HttpResponseRedirect(reverse('enigmaControl:presupuestos'))

class crearPresupuesto(LoginRequiredMixin, FormView):
    template_name = 'enigmaControl/formularios/crearPresupuesto.html'
    form_class = presupuestoTablaForm
    success_url = 'enigmaControl:presupuestos'

    def form_valid(self, form):
        form.save(commit=False)
        form.instance.usuario = self.request.user
        form.save()
        messages.success(self.request, 'Presupuesto creado éxitosamente!')
        return HttpResponseRedirect(reverse(self.success_url))
    
    def form_invalid(self, form):
        messages.error(self.request, messages.error)
        return super().form_invalid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Crear Presupuesto - Enigma'
        context['version'] = '1.0.1'
        context['subtitle'] = 'Registro de nuevo presupuesto'
        context['clientes'] = MantenimientoClientes.objects.filter(Usuario=self.request.user)
        return context



class actualizarPresupuesto(LoginRequiredMixin, UpdateView):
    model = PresupuestoTabla
    form_class = presupuestoTablaForm
    template_name = 'enigmaControl/formularios/crearPresupuesto.html'
    success_url = 'enigmaControl:presupuestos'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Editar presupuesto - Enigma'
        context['version'] = '1.0.1'
        context['subtitle'] = 'Editar Presupuesto'
        return context

    def get_success_url(self):
        messages.success(self.request, 'Reporte actualizado con éxito!')
        return reverse_lazy(self.success_url)

def eliminarPresupuestoTabla(request, id):
    presupuesto = PresupuestoTabla.objects.get(id=id)
    presupuesto.delete()
    messages.success(request, 'Presupuesto eliminado con éxito!')
    return HttpResponseRedirect(reverse('enigmaControl:presupuestos'))


class presupuestosViewSet(viewsets.ModelViewSet):
    queryset = PresupuestoTabla.objects.all()
    serializer_class = PresupuestoTablaSerializer

class usuariosViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UsuariosSerializer
    

templates/enigmaControl/dashboardControl.html
{% extends "baseDashboard.html" %}

{% load static %}

{% block content %}

  

  <div class="main-content" data-aos="fade-down">
    <p class="text-center h2">Modulo de control de {{user.username}}</p>
    <div class="container">
        <div class="row text-center my-3">
            <div class="col-lg-4 col-12">
                <div class="small-box bg-success shadow-lg">
                    <div class="inner">
                        <h3>{{visitas}}<sup style="font-size: 20px"></sup></h3>
                        <p>Visitas registradas</p>
                    </div>
                    <div class="icon">
                        <i class="fas fa-users"></i>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-12">
                <div class="small-box bg-primary shadow-lg">
                    <div class="inner">
                        <h3>{{reportes}}<sup style="font-size: 20px"></sup></h3>
                        <p>Reportes registrados</p>
                    </div>
                    <div class="icon">
                        <i class="fas fa-layer-group"></i>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-12">
                <div class="small-box bg-indigo shadow-lg">
                    <div class="inner">
                        <h3>0<sup style="font-size: 20px"></sup></h3>
                        <p>Presupuestos</p>
                    </div>
                    <div class="icon">
                        <i class="fas fa-coins"></i>
                    </div>
                </div>
            </div>
        </div>

        <div class="row my-3">
            <div class="col-lg-4 col-12">
                <div class="card text-center" >
                    <div class="card-header">
                      Registrar nueva visita
                      <i class="fas fa-file"></i>
                    </div>
                    <div class="card-body">
                      <p class="card-text text-center">Cada que se registre una nueva visita recurre a llenar este formato.</p>
                      <a href="{% url 'enigmaControl:crearVisita' %}" class="btn btn-primary">¡Vamos!</a>
                    </div>
                  </div>
              </div>

              <div class="col-lg-4 col-12">
                <div class="card text-center" >
                    <div class="card-header">
                      Registrar nuevo reporte
                      <i class="fas fa-file"></i>
                    </div>
                    <div class="card-body">
                      <p class="card-text text-center">Cada que se registre un nuevo reporte recurre a llenar este formato.</p>
                      <a href="{% url 'enigmaControl:crearReporte' %}" class="btn btn-primary">¡Vamos!</a>
                    </div>
                  </div>
              </div>

              <div class="col-lg-4 col-12">
                <div class="card text-center" >
                    <div class="card-header">
                      Crear nuevo presupuesto
                      <i class="fas fa-file"></i>
                    </div>
                    <div class="card-body">
                      <p class="card-text text-center">Crea un nuevo presupuesto mensual</p>
                      <a href="{% url 'enigmaControl:presupuestos' %}" class="btn btn-primary">¡Vamos!</a>
                    </div>
                  </div>
              </div>
        </div>

        <div class="table-responsive">
            <p class="text-center h2 my'3">Control de presupuestos</p>
            <table id="tablaPresupuestos" class="table align-middle mb-5">
                <thead>
                    <tr>
                        <th>Fecha</th>
                        <th>Razón social</th>
                        <th>Objetivo de venta</th>
                        <th>Real de venta</th>
                        <th>Objetivo cobranza</th>
                        <th>Real cobranza</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for presupuesto in presupuestos %}
                        <tr>
                            <td>{{presupuesto.periodo}}</td>
                            <td>{{presupuesto.cliente}}</td>
                            <td>{{presupuesto.objetivo}}</td>
                            <td>{{presupuesto.real}}</td>
                            <td>{{presupuesto.objetivoCobranza}}</td>
                            <td>{{presupuesto.realCobranza}}</td>
                            <td>
                                <a href="{% url 'enigmaControl:editarPresupuesto' presupuesto.pk %}" class="btn btn-primary">
                                    <i class="fas fa-pen"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="table-responsive">
            <p class="text-center h2">Registro de visitas</p>
            <table id="tablaVisitas" class="table align-middle mb-5">
                <thead>
                    <tr>
                        <th>Fecha</th>
                        <th>Duración de visita</th>
                        <th>Nombre</th>
                        <th>Razón de visita</th>
                        <th>Observaciones</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for visita in visitasTabla %}
                        <tr>
                            <td>{{visita.fecha}}</td>
                            <td>{{visita.duracionVisita}} Hrs.</td>
                            <td>{{visita.nombreVisita}}</td>
                            <td>{{visita.razonVisita}}</td>
                            <td>{{visita.observaciones}}</td>
                            <td>
                                <a href="{% url 'enigmaControl:editarVisita' visita.pk %}" class="btn btn-primary">
                                    <i class="fas fa-pen"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="table-responsive my-3">
            <p class="text-center h2">Registro de reportes</p>
            <table id="tablaReportes" class="table align-middle mb-5">
                <thead>
                    <tr>
                        <th>Fecha de el reporte</th>
                        <th>Nombre</th>
                        <th>Notificar reporte a</th>
                        <th>Razón/observaciones</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for reporte in reportesTabla %}
                        <tr>
                            <td>{{reporte.fechaReporte}}</td>
                            <td>{{reporte.nombreReporte}}</td>
                            <td>{{reporte.notificarReporte}}</td>
                            <td>{{reporte.descripcionReporte}}</td>
                            <td>
                                <a href="{% url 'enigmaControl:editarReporte' reporte.pk %}" class="btn btn-primary">
                                    <i class="fas fa-pen"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
  </div>







{% endblock content %}

{% block scripts %}
  <script>
      $(document).ready(function () {
            $('#tablaVisitas').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                },
                responsive: false,
            });
        });

        $(document).ready(function () {
            $('#tablaReportes').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                },
                responsive: false,
            });
        });

        $(document).ready(function () {
            $('#tablaPresupuestos').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                },
                responsive: false,
            });
        });
  </script>
{% endblock scripts %}