core/enigmaVentas/urls.py
from django.urls import path
from core.enigmaVentas.views import *

app_name = 'enigmaVentas'

urlpatterns = [
    path('', dashboardVentas.as_view(), name='dashboardVentas'),
    # MANTENIMIENTO DE PROSPECTOS
    path('crear-prospecto/', crearProspecto.as_view(), name='crearProspecto'),
    path('editar-prospecto/<int:pk>/', editarProspecto.as_view(), name='editarProspecto'),
    path('pdf-prospecto/<int:id>/', crearPdfProspectos, name='pdfProspecto'),
    # MANTENIMIENTO DE CLIENTES
    path('crear-cliente/', crearCliente.as_view(), name='crearCliente'),
    path('editar-cliente/<int:pk>/', editarCliente.as_view(), name='editarCliente'),
    path('pdf-cliente/<int:id>/', crearPdfClientes, name='pdfCliente'),
    # SOLICITUD DE CREDITO
    path('solicitud-credito/', crearCredito.as_view(), name='solicitudCredito'),
    path('editar-credito/<int:pk>/', editarCredito.as_view(), name='editarCredito'),
    path('pdf-credito/<int:id>/', crearPdfCreditos, name='pdfCredito'),
    # PEDIDOS
    path('crear-pedido/', pedidosView.as_view(), name='crearPedido'),
    # PRODUCTOS
    path('ver-productos/', verProductos.as_view(), name='verProductos'),
]

system/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from core.enigmaControl.views import presupuestosViewSet, usuariosViewSet
from system import settings
from django.conf.urls.static import static

router = DefaultRouter()
router.register(r'usuarios', usuariosViewSet)
router.register(r'presupuestos', presupuestosViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.enigma.urls')),
    # URLS DE ENIGMA
    path('erp/', include('core.enigmaErp.urls')),
    path('control/', include('core.enigmaControl.urls')),
    path('ventas/', include('core.enigmaVentas.urls')),
    path('administracion/', include('core.enigmaAdmin.urls')),\
    # URLS DE MULTIPOLIMEROS
    path('multipolimeros/', include('core.multipolimeros.urls')),
    # URLS DE TERCEROS
    path('accounts/', (include(('django.contrib.auth.urls', 'auth'), namespace='auth' ))),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include(router.urls)), 
]

if settings.DEBUG:
    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/enigmaVentas/forms.py
from django import forms
from core.enigmaVentas.models import *


class mantenimientoProspectosForm(forms.ModelForm):
    class Meta:
        model = MantenimientoProspectos
        exclude = ['Usuario']
        fields = '__all__'


class mantenimiendoClientesForm(forms.ModelForm):
    class Meta:
        model = MantenimientoClientes
        exclude = ['Usuario']
        fields = '__all__'


class solicitudCreditoForm(forms.ModelForm):
    class Meta:
        model = SolicitudCredito
        exclude = ['Usuario']
        fields = '__all__'
        widgets={
            'DocumentosEntregados': forms.CheckboxSelectMultiple(attrs={'class':'form-control col-lg-12'}),
        }

core/enigmaVentas/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, FormView, UpdateView
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# WEASYPRINT
from django.template.loader import render_to_string
# MODELOS Y FORMS
from core.enigmaVentas.models import *
from core.enigmaVentas.forms import *
from xhtml2pdf import pisa


class dashboardVentas(LoginRequiredMixin,TemplateView):
    template_name = 'enigmaVentas/dashboardVentas.html'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Ventas - Enigma'
        context['version'] = '1.0.1'
        context['prospectos'] = MantenimientoProspectos.objects.filter(Usuario=self.request.user)
        context['clientes'] = MantenimientoClientes.objects.filter(Usuario=self.request.user)
        context['creditos'] = SolicitudCredito.objects.filter(Usuario=self.request.user)
        return context


# VISTAS DEL MANTEMINTO DE PROSPECTOS


class crearProspecto(LoginRequiredMixin,FormView):
    template_name = 'enigmaVentas/formularios/prospecto.html'
    form_class = mantenimientoProspectosForm
    success_url = 'enigmaVentas:dashboardVentas'
    

    def form_valid(self, form):
        form.save(commit=False)
        form.instance.Usuario = self.request.user
        form.save()
        messages.success(self.request, '¡Prospecto creado exitosamente!')
        return HttpResponseRedirect(reverse(self.success_url))

    def form_invalid(self, form):
        messages.error(self.request, '¡Algo ha salido mal!')
        print(form.errors)
        return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Agregar prospecto - Enigma'
        context['version'] = '1.0.1'
        context['subtitle'] = 'Registro de nuevo prospecto'
        return context


class editarProspecto(LoginRequiredMixin, UpdateView):
    model = MantenimientoProspectos
    form_class = mantenimientoProspectosForm
    template_name = 'enigmaVentas/formularios/prospecto.html'
    success_url = 'enigmaVentas:dashboardVentas'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Editar prospecto - Enigma'
        context['version'] = '1.0.1'
        context['subtitle'] = 'Edición de prospecto'
        return context

    def get_success_url(self):
        messages.success(self.request, 'Prospecto actualizado con éxito!')
        return reverse(self.success_url)


@login_required
def crearPdfProspectos(request, id):
    prospecto = MantenimientoProspectos.objects.get(id=id)
    html_string = render_to_string('pdf/enigmaVentas/prospecto.html', {'prospecto': prospecto})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = ' filename="prospecto.pdf"'
    pisa.CreatePDF(html_string, response)
    return response


# VISTAS DEL MANTEMINTO DE CLIENTES


class crearCliente(LoginRequiredMixin,FormView):
    template_name = 'enigmaVentas/formularios/cliente.html'
    form_class = mantenimiendoClientesForm
    success_url = 'enigmaVentas:dashboardVentas'
    

    def form_valid(self, form):
        form.save(commit=False)
        form.instance.Usuario = self.request.user
        form.save()
        messages.success(self.request, 'Cliente creado exitosamente!')
        return HttpResponseRedirect(reverse(self.success_url))

    def form_invalid(self, form):
        messages.error(self.request, 'Faltan campos por llenar!')
        print(form.errors)
        return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Agregar cliente - Enigma'
        context['version'] = '1.0.1'
        context['subtitle'] = 'Registro de nuevo cliente'
        return context


class editarCliente(LoginRequiredMixin, UpdateView):
    model = MantenimientoClientes
    form_class = mantenimiendoClientesForm
    template_name = 'enigmaVentas/formularios/cliente.html'
    success_url = 'enigmaVentas:dashboardVentas'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Editar cliente - Enigma'
        context['version'] = '1.0.1'
        context['subtitle'] = 'Edición de cliente'
        return context

    def get_success_url(self):
        messages.success(self.request, 'Cliente actualizado con éxito!')
        return reverse(self.success_url)


@login_required
def crearPdfClientes(request, id):
    cliente = MantenimientoClientes.objects.get(id=id)
    html_string = render_to_string('pdf/enigmaVentas/cliente.html', {'cliente': cliente})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = ' filename="cliente.pdf"'
    pisa.CreatePDF(html_string, response)
    return response


# VISTAS DEL MANTENIMIENTO DE CREDITO


class crearCredito(LoginRequiredMixin,FormView):
    template_name = 'enigmaVentas/formularios/credito.html'
    form_class = solicitudCreditoForm
    success_url = 'enigmaVentas:dashboardVentas'
    

    def form_valid(self, form):
        form.save(commit=False)
        form.instance.Usuario = self.request.user
        form.save()
        messages.success(self.request, 'Solicitud de crédito creada exitosamente!')
        return HttpResponseRedirect(reverse(self.success_url))

    def form_invalid(self, form):
        messages.error(self.request, '¡Algo ha salido mal!')
        print(form.errors)
        return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Solicitud crédito - Enigma'
        context['version'] = '1.0.1'
        context['subtitle'] = 'Registro de nuevo crédito'
        return context


class editarCredito(LoginRequiredMixin, UpdateView):
    model = SolicitudCredito
    form_class = solicitudCreditoForm
    template_name = 'enigmaVentas/formularios/credito.html'
    success_url = 'enigmaVentas:dashboardVentas'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Editar crédito - Enigma'
        context['version'] = '1.0.1'
        context['subtitle'] = 'Edición de crédito'
        return context

    def get_success_url(self):
        messages.success(self.request, 'Crédito actualizado con éxito!')
        return reverse(self.success_url)


@login_required
def crearPdfCreditos(request, id):
    credito = SolicitudCredito.objects.get(id=id)
    html_string = render_to_string('pdf/enigmaVentas/credito.html', {'credito': credito})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = ' filename="credito.pdf"'
    pisa.CreatePDF(html_string, response)
    return response


# VISTAS DEL MANTENIMIENTO DE PEDIDOS

class pedidosView(TemplateView):
    template_name = 'enigmaVentas/ventas.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Modulo deshabilitado'
        return context


# VISTAS DE PRODUCTOS


class verProductos(LoginRequiredMixin, TemplateView):
    template_name = 'enigmaVentas/productos.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Productos - Enigma'
        context['version'] = '1.0.1'
        context['productos'] = Productos.objects.all()
        return context

templates/enigmaVentas/dashboardVentas.html
{% extends "baseDashboard.html" %}

{% load static %}

{% block content %}
  
<div class="main-content" data-aos="fade-down">
    <p class="text-center h2">Modulo de ventas de {{user.username}}</p>
    <div class="container">
        <div class="row text-center my-3">
            <div class="col-lg-3 col-12">
                <div class="small-box bg-success shadow-lg">
                    <div class="inner">
                        <h3>{{prospectos.count}}<sup style="font-size: 20px"></sup></h3>
                        <p>Prospectos registrados</p>
                    </div>
                    <div class="icon">
                        <i class="fas fa-users"></i>
                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-12">
                <div class="small-box bg-indigo shadow-lg">
                    <div class="inner">
                        <h3>{{clientes.count}}<sup style="font-size: 20px"></sup></h3>
                        <p>Clientes registrados</p>
                    </div>
                    <div class="icon">
                        <i class="fas fa-user"></i>
                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-12">
                <div class="small-box bg-indigo shadow-lg">
                    <div class="inner">
                        <h3>{{creditos.count}}<sup style="font-size: 20px"></sup></h3>
                        <p>Créditos registrados</p>
                    </div>
                    <div class="icon">
                        <i class="fas fa-coins"></i>
                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-12">
                <div class="small-box bg-indigo shadow-lg">
                    <div class="inner">
                        <h3>0<sup style="font-size: 20px"></sup></h3>
                        <p>Pedidos registrados</p>
                    </div>
                    <div class="icon">
                        <i class="fas fa-box"></i>
                    </div>
                </div>
            </div>
        </div>

        <div class="row my-3">
            <div class="col-lg-3 col-12">
                <div class="card text-center" >
                    <div class="card-header">
                      Registrar nuevo prospecto
                      <i class="fas fa-users"></i>
                    </div>
                    <div class="card-body">
                      <p class="card-text text-center">Manten tu registro de prospectos actualizado.</p>
                      <a href="{% url 'enigmaVentas:crearProspecto' %}" class="btn btn-primary">¡Vamos!</a>
                    </div>
                  </div>
              </div>

              <div class="col-lg-3 col-12">
                <div class="card text-center" >
                    <div class="card-header">
                      Registrar nuevo cliente
                      <i class="fas fa-user"></i>
                    </div>
                    <div class="card-body">
                      <p class="card-text text-center">Cuando un prospecto se vuelva cliente, migra la información aquí.</p>
                      <a href="{% url 'enigmaVentas:crearCliente' %}" class="btn btn-primary">¡Vamos!</a>
                    </div>
                  </div>
              </div>

              <div class="col-lg-3 col-12">
                <div class="card text-center" >
                    <div class="card-header">
                      Registrar nuevo crédito
                      <i class="fas fa-coins"></i>
                    </div>
                    <div class="card-body">
                      <p class="card-text text-center">Cuando tu cliente quiera requerir un crédito, llena este formulario.</p>
                      <a href="{% url 'enigmaVentas:solicitudCredito' %}" class="btn btn-primary">¡Vamos!</a>
                    </div>
                  </div>
              </div>

              <div class="col-lg-3 col-12">
                <div class="card text-center" >
                    <div class="card-header">
                      Registrar nuevo pedido
                      <i class="fas fa-box"></i>
                    </div>
                    <div class="card-body">
                      <p class="card-text text-center">Manejo de pedidos de tus clientes, recuerda llenarlo correctamente.</p>
                      <a href="{% url 'enigmaVentas:crearPedido' %}" class="btn btn-primary">¡Vamos!</a>
                    </div>
                  </div>
              </div>


              <div class="col-lg-3 col-12">
                <div class="card text-center" >
                    <div class="card-header">
                      Productos
                      <i class="fas fa-cart-plus"></i>
                    </div>
                    <div class="card-body">
                      <p class="card-text text-center">Gestiona los productos disponibles, consulta precios.</p>
                      <a href="{% url 'enigmaVentas:verProductos' %}" class="btn btn-primary">¡Vamos!</a>
                    </div>
                  </div>
              </div>
        </div>

        <div class="table-responsive my-3">
            <p class="text-center h2">Registro de prospectos</p>
            <table id="tablaProspectos" class="table align-middle mb-5">
                <thead>
                    <tr>
                        <th>Fecha</th>
                        <th>Razón social</th>
                        <th>RFC</th>
                        <th>Correo</th>
                        <th>Celular</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for p in prospectos %}
                        <tr>
                            <td>{{p.Fecha}}</td>
                            <td>{{p.RazonSocial}}</td>
                            <td>{{p.Rfc}}</td>
                            <td>{{p.CorreoElectronico}}</td>
                            <td>{{p.TelefonoCelular}}</td>
                            <td>
                                <a href="{% url 'enigmaVentas:editarProspecto' p.pk %}" class="btn btn-primary">
                                    <i class="fas fa-pen"></i>
                                </a>
                                <a href="{% url 'enigmaVentas:pdfProspecto' p.id %}" class="btn btn-success">
                                    <i class="fas fa-file-pdf"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="table-responsive my-3">
            <p class="text-center h2 my-3">Registro de clientes</p>
            <table id="tablaClientes" class="table align-middle mb-5">
                <thead>
                    <tr>
                        <th>Fecha</th>
                        <th>Razón social</th>
                        <th>RFC</th>
                        <th>Correo</th>
                        <th>Celular</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for c in clientes %}
                        <tr>
                            <td>{{c.Fecha}}</td>
                            <td>{{c.RazonSocial}}</td>
                            <td>{{c.Rfc}}</td>
                            <td>{{c.CorreoElectronico}}</td>
                            <td>{{c.TelefonoCelular}}</td>
                            <td>
                                <a href="{% url 'enigmaVentas:editarCliente' c.pk %}" class="btn btn-primary">
                                    <i class="fas fa-pen"></i>
                                </a>
                                <a href="{% url 'enigmaVentas:pdfCliente' c.id %}" class="btn btn-success">
                                    <i class="fas fa-file-pdf"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="table-responsive my-3">
            <p class="text-center h2">Registro de créditos</p>
            <table id="tablaCreditos" class="table align-middle mb-5">
                <thead>
                    <tr>
                        <th>Fecha</th>
                        <th>Razón social</th>
                        <th>RFC</th>
                        <th>Correo</th>
                        <th>Celular</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for credito in creditos %}
                        <tr>
                            <td>{{credito.Fecha}}</td>
                            <td>{{credito.RazonSocial}}</td>
                            <td>{{credito.Rfc}}</td>
                            <td>{{credito.CorreoElectronico}}</td>
                            <td>{{credito.TelefonoCelular}}</td>
                            <td>
                                <a href="{% url 'enigmaVentas:editarCredito' credito.pk %}" class="btn btn-primary">
                                    <i class="fas fa-pen"></i>
                                </a>
                                <a href="{% url 'enigmaVentas:pdfCredito' credito.id %}" class="btn btn-success">
                                    <i class="fas fa-file-pdf"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock content %}


{% block scripts %}
  <script>
      $(document).ready(function () {
            $('#tablaProspectos').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                },
                responsive: false,
            });

             $('#tablaClientes').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                },
                responsive: false,
            });

            $('#tablaCreditos').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                },
                responsive: false,
            });
        });
  </script>
{% endblock scripts %}

templates/enigmaVentas/productos.html
{% extends "baseDashboard.html" %}

{% load static %}

{% block content %}
  <div class="main-content" data-aos="fade-down">
    <p class="text-center h2">Listado de productos</p>
    <div class="container">
       

      <div class="table-responsive my-3">
        <table id="tablaProductos" class="table align-middle mb-5">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Codigo de linea</th>
                    <th>Codigo de color</th>
                    <th>Descripción</th>
                    <th>Precio LPA</th>
                    <th>Precio LPD</th>
                </tr>
            </thead>
            <tbody>
                {% for p in productos %}
                    <tr>
                        <td>{{ p.id }}</td>
                        <td>{{p.codLinea}}</td>
                        <td>{{p.codColor}}</td>
                        <td>{{p.descripcion}}</td>
                        <td>{{p.lpa}}</td>
                        <td>{{p.lpd}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>


    </div>
  </div>
{% endblock content %}

{% block scripts %}
  <script>
    $(document).ready(function () {
        $('#tablaProductos').DataTable({
          "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                },
        });
      });
  </script>
{% endblock scripts %}

templates/enigmaVentas/ventas.html
<!DOCTYPE html>
<html lang="es-mx">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>{{title}}</title>
</head>
<style>
    body{
        font-family: 'Poppins', sans-serif;
    }
</style>
<body class=" min-h-100">
    <div class="container">
        <div class="my-5 text-center">
            <img src="https://svgsilh.com/svg/151670.svg" width="100" class="my-4">
            <p class="h2">Modulo 22sh34c deshabilitado por un administrador.</p>
            
            <p class="my-3 text-muted">Verifique el status de la carga de modulos para habilitar o deshabilitar modulos.</p>
        </div>
    </div>




    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>