core/enigmaAdmin/urls.py
from django.urls import path
from core.enigmaAdmin.views import *

app_name = 'enigmaAdmin'


urlpatterns = [
    path('', dashboardAdmin.as_view(), name='dashboardAdmin'),
    path('personal/<int:pk>/', gestionPersonal.as_view(), name='gestionPersonal'),
    path('presupuestos/', administrarPresupuestos.as_view(), name='administrarPresupuestos'),
    path('presupuestos/<int:pk>/', tablaPresupuestos.as_view(), name='tablaPresupuestos'),
]

core/enigmaControl/urls.py
from django.urls import path
from core.enigmaControl.views import *

app_name = 'enigmaControl'

urlpatterns = [
    path('', dashboardControl.as_view(), name='indexControl'),
    # CONTROL DE VISITAS
    path('crear-visita/', crearControlVisitas.as_view(), name='crearVisita'),
    path('editar-visita/<int:pk>/', editarControlVisitas.as_view(), name='editarVisita'),
    # CONTROL DE REPORTES
    path('crear-reporte/', crearControlReportes.as_view(), name='crearReporte' ),
    path('editar-reporte/<int:pk>', editarControlReportes.as_view(), name='editarReporte'),
    # CONTROL DE PRESUPUESTOS
    path('presupuestos/', presupuestos.as_view(), name='presupuestos'),
    path('eliminar-presupuesto/<int:id>', eliminarPresupuesto, name='eliminarPresupuesto'),
    path('editar-presupuesto/<int:pk>', actualizarPresupuesto.as_view(), name='editarPresupuesto'),
    path('crear-presupuesto/', crearPresupuesto.as_view(), name='crearPresupuesto'),
    path('eliminar-presupuesto-tabla/<int:id>', eliminarPresupuestoTabla, name='eliminarPresupuestoTabla')
]

core/enigmaErp/urls.py
from django.urls import path 
from core.enigmaErp.views import dashboardView

app_name = 'enigmaErp'

urlpatterns = [
    path('', dashboardView.as_view(), name='dashboard'),
]

core/enigmaVentas/urls.py
from django.urls import path
from core.enigmaVentas.views import *

app_name = 'enigmaVentas'

urlpatterns = [
    path('', dashboardVentas.as_view(), name='dashboardVentas'),
    # MANTENIMIENTO DE PROSPECTOS
    path('crear-prospecto/', crearProspecto.as_view(), name='crearProspecto'),
    path('editar-prospecto/<int:pk>/', editarProspecto.as_view(), name='editarProspecto'),
    path('pdf-prospecto/<int:id>/', crearPdfProspectos, name='pdfProspecto'),
    # MANTENIMIENTO DE CLIENTES
    path('crear-cliente/', crearCliente.as_view(), name='crearCliente'),
    path('editar-cliente/<int:pk>/', editarCliente.as_view(), name='editarCliente'),
    path('pdf-cliente/<int:id>/', crearPdfClientes, name='pdfCliente'),
    # SOLICITUD DE CREDITO
    path('solicitud-credito/', crearCredito.as_view(), name='solicitudCredito'),
    path('editar-credito/<int:pk>/', editarCredito.as_view(), name='editarCredito'),
    path('pdf-credito/<int:id>/', crearPdfCreditos, name='pdfCredito'),
    # PEDIDOS
    path('crear-pedido/', pedidosView.as_view(), name='crearPedido'),
    # PRODUCTOS
    path('ver-productos/', verProductos.as_view(), name='verProductos'),
]

system/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from core.enigmaControl.views import presupuestosViewSet, usuariosViewSet
from system import settings
from django.conf.urls.static import static

router = DefaultRouter()
router.register(r'usuarios', usuariosViewSet)
router.register(r'presupuestos', presupuestosViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.enigma.urls')),
    # URLS DE ENIGMA
    path('erp/', include('core.enigmaErp.urls')),
    path('control/', include('core.enigmaControl.urls')),
    path('ventas/', include('core.enigmaVentas.urls')),
    path('administracion/', include('core.enigmaAdmin.urls')),\
    # URLS DE MULTIPOLIMEROS
    path('multipolimeros/', include('core.multipolimeros.urls')),
    # URLS DE TERCEROS
    path('accounts/', (include(('django.contrib.auth.urls', 'auth'), namespace='auth' ))),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include(router.urls)), 
]

if settings.DEBUG:
    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es-mx">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <!--Google fonts POPPINS-->
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
    <!--Font awesome icons-->
    <link rel="stylesheet" href="{% static 'adminlte/plugins/fontawesome/css/all.min.css' %}">
    <!--Aos Js-->
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <!--Adminlte css-->
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/adminlte.min.css' %}">
    <!-- Css personalizado-->
    <link rel="stylesheet" href="{% static 'resources/css/main.css' %}">
    {% block head %}
      
    {% endblock head %}
</head>
<body>
    {% block content %}
      
    {% endblock content %}
    <!--Jquery-->
    <script src="{% static 'adminlte/plugins/jquery/jquery.min.js' %}"></script>
    <!--Bootstrap bundle js-->
    <script src="{% static 'adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!--Adminlte js-->
    <script src="{% static 'adminlte/dist/js/adminlte.min.js' %}"></script>
    <!--Aos Js-->
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
      AOS.init();
    </script>
    {% block scripts %}
      
    {% endblock scripts %}
</body>
</html>

templates/baseDashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="es-mx">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <!--Google fonts POPPINS-->
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
    <!--Font awesome icons-->
    <link rel="stylesheet" href="{% static 'adminlte/plugins/fontawesome/css/all.min.css' %}">
    <!--Aos Js-->
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <!--Intro js-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/intro.js/5.1.0/introjs.min.css">
    <!--Date range picker css-->
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
    <!--Datatables css-->
    <link rel="stylesheet" href="//cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css">
    <!--Bs stepper-->
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/bs-stepper/dist/css/bs-stepper.min.css">
    <!--Select 2-->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <!--Adminlte css-->
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/adminlte.min.css' %}" type="">
    <!-- Css personalizado-->
    <link rel="stylesheet" href="{% static 'resources/css/main.css' %}">
    {% block head %}
      
    {% endblock head %}
</head>
<body class="d-flex flex-column min-vh-100">
    <div class="w-100">      
        <!-- Content Wrapper. Contains page content -->
        <div class="container-fluid">
          <!-- Content Header (Page header) -->
          <div class="content-header" data-aos="fade-up">
              <div class="row mb-2">
                <div class="d-flex col-sm-4 align-items-center">
                  <img src="{% static 'resources/img/rubik.svg' %}" alt="LOGO-ENIGMA-RUBIK" srcset="" width="35px">
                  <h1 class="m-0 mx-3">Enigma</h1>
                </div>
                <div class="col-sm-8 py-2 d-none d-lg-block">
                  <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item active"><a href="{% url 'multipolimeros:dashboard' %}">Multipolimeros</a></li>
                    <li class="breadcrumb-item"><a href="">{{version}}</a></li>
                    <li class="breadcrumb-item active">{{user.get_full_name}}</li>
                    <li class="breadcrumb-item active">Ultima conexión: {{user.last_login}}</li>
                  </ol>
                </div>
              </div>
          </div>


          

          {% block content %}
            
          {% endblock content %}
         
         
         
          <br>
          <br>
          <br>
          <br>
          <nav class="navbar fixed-bottom navbar-expand-lg bg-white py-1">
            <div class="container-fluid d-flex m-0 py-2 justify-content-center" >
                <ul class="nav nav-pills text-center" data-title="Barra de navegación" data-intro="La barra de navegación contiene los mismos elementos que los módulos ya mencionados, siempre estará disponible cuando navegues en Enigma, facilitándote el traslado entre secciones">
                  <li class="nav-item bg-primary rounded mx-2">
                    <a href="{% url 'enigmaErp:dashboard' %}" class="nav-link py-2" aria-current="page" title="Inicio" data-bs-toggle="tooltip" data-bs-placement="top">
                        <i class="fas fa-home"></i>
                    </a>
                  </li>  
                  <li class="nav-item bg-primary rounded mx-2">
                        <a href="{% url 'enigmaVentas:dashboardVentas' %}" class="nav-link py-2" aria-current="page" title="Ventas" data-bs-toggle="tooltip" data-bs-placement="top">
                            <i class="fas fa-coins"></i>
                        </a>
                    </li>
                    <li class="nav-item bg-primary rounded mx-2">
                        <a href="{% url 'enigmaControl:indexControl' %}" class="nav-link py-2" aria-current="page" title="Control" data-bs-toggle="tooltip" data-bs-placement="top">
                            <i class="fas fa-file"></i>
                        </a>
                    </li>
                    {% if request.user.is_superuser %}
                    <li class="nav-item bg-primary rounded mx-2">
                        <a href="{% url 'enigmaAdmin:dashboardAdmin' %}" class="nav-link py-2" aria-current="page" title="Administrador" data-bs-toggle="tooltip" data-bs-placement="top">
                            <i class="fas fa-stream"></i>
                        </a>
                    </li>
                    {% endif %}
                    <li class="nav-item bg-danger rounded mx-2" data-title="Cerrar sesión" data-intro="Este botón sirve para cerrar sesión, asegúrate de guardar tus datos antes de abandonar Enigma, esto es todo, ya has comprendido como utilizar el sistema ¡Que tengas un día lleno de éxito!">
                        <a href="{% url 'auth:logout' %}" class="nav-link py-2" aria-current="page" title="Cerrar sesión" data-bs-toggle="tooltip" data-bs-placement="top">
                            <i class="fa fa-user-times"></i>
                        </a>
                    </li>
                    
                </ul>
            </div>
          </nav>

        </div>
    </div>
      <!-- ./wrapper -->
    <!--Jquery-->
    <script src="{% static 'adminlte/plugins/jquery/jquery.min.js' %}"></script>
    <!--BS STEPPER-->
    <script src="//cdn.jsdelivr.net/npm/bs-stepper/dist/js/bs-stepper.min.js"></script>
    <!--Bootstrap bundle js-->
    <script src="{% static 'adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!--Adminlte js-->
    <script src="{% static 'adminlte/dist/js/adminlte.min.js' %}"></script>
    <!--Aos Js-->
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <!--Sweet alert-->
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    {% if messages %}
      {% for m in messages %}
              <script>
                Swal.fire({
                  icon: '{{m.tags}}',
                  title: '{{m}}',
                  text: "{{m}}",
                  showConfirmButton: false,
                  timer: 3000,
                });
              </script>
      {% endfor %}
    {% endif %}
    <!--Datatables-->
    <script src="//cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/plug-ins/1.10.15/i18n/Spanish.json"></script>
    <!--Chart js-->
    <script src="{% static 'adminlte/plugins/chartjs/Chart.min.js'  %}"></script>
    <!--Date picker js-->
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <!--Aos init-->
    <script>
      AOS.init();
    </script>
    <!--Intro js-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/intro.js/5.1.0/intro.min.js"></script>
    <!--select2 js-->
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    
    <script>
      introJs().setOptions({
        "dontShowAgain" : true,
        "dontShowAgainLabel" : "No mostrar de nuevo",
        "nextLabel" : "Siguiente",
        "prevLabel" : "Anterior",
        "doneLabel" : "Hecho",
      }).start();
    </script>
    {% block scripts %}
      
    {% endblock scripts %}
</body>
</html>